[package]
name = "rename_files"
version = "0.1.0"
authors = ["Arjun <arjunnair2k18@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.2.16"
